[features]
seeds = false
skip-lint = false
[programs.localnet]
tap_cash = "TAPAPp2YoguQQDkicGyzTzkA3t4AgECvR1eL1hbx9qz"

[programs.devnet]
tap_cash = "TAPAPp2YoguQQDkicGyzTzkA3t4AgECvR1eL1hbx9qz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
